name: funkysundays
services:
    backend:
        build: ./backend
        container_name: backend
        restart: unless-stopped
        ports:
            - 8090:8090
        networks:
            - funkysundays
    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
            network: host
        container_name: frontend
        restart: unless-stopped
        networks:
            - funkysundays
networks:
    funkysundays:
        external: true
