version: "3.7"
name: funkysundays
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        volumes:
            - ./pb_data:/pb_data
            - ./pb_migrations:/pb_migrations
        networks:
            - funkysundays
    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        restart: unless-stopped
        networks:
            - funkysundays
networks:
    funkysundays:
        external: true
