name: funkysundays
services:
    backend:
        build: ./backend
        container_name: funkysundays-backend
        restart: unless-stopped
        ports:
            - 8090:8090
        networks:
            - traefik_proxy
    frontend:
        depends_on:
            - backend
        build: ./frontend
        container_name: funkysundays-frontend
        restart: unless-stopped
        networks:
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.funkysundays.loadbalancer.server.port=3000"
            - "traefik.http.routers.funkysundays.rule=Host(`funkysundays.smkg.me`)"
            - "traefik.http.routers.funkysundays.entrypoints=websecure"
            - "traefik.http.routers.funkysundays.tls.certresolver=letsencrypt"
networks:
    traefik_proxy:
        external: true
