name: Deployment Workflow
on:
    push:
        branches:
            - release
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Install dependencies
                run: npm install
            -   name: Build Next.js app
                run: npm run build
                env:
                    -   POCKETBASE_URL: ${{ secrets.DATABASE_URL }}
            -   name: SSH Deploy
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        cd ~/funkysundays
                        git pull
                        npm install
                        npm run build
                        pm2 restart funkysundays
